config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    match '/', to: 'events#create', via: [:post, :options]
  end

  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
  resources :sessions

  get 'sign_up', to: 'users#new', as: 'sign_up'
  resources :users

  resources :registered_applications

  get 'welcome/about'
  root to: 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password, :current_password
  has_many :registered_applications, dependent: :destroy
  before_save :encrypt_password

  validates :email, presence: true, uniqueness: true,
    format: { with: /(@)\w+\./, message: 'Email address is not valid.' }
  validates :password, confirmation: true, presence: true, length: { minimum: 5 }
  validate :check_current_password, on: :update

  def check_current_password
    if !password.blank?
      unless self.class.authenticate(self.email, self.current_password)
        errors.add(:current_password, "is incorrect.") 
      end
    end
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :cors_preflight_check
  after_action :cors_set_access_control_headers

  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'content-type'

      render json: '', content_type: 'text-plain'
    end
  end

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'content-type'
  end

  def create
    application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = application.events.build(event_params)

      if @event.save!
        render json: @event, status: :created
      else
        render @event.errors, status: :unprocessable_entity
      end
    end
  end

  private

  def event_params
    params.permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :authorized?

  private
  
  def current_user
    warden.user
  end

  def warden
    env['warden']
  end

  def authorized?(record)
    unless record.user == current_user
      raise "Not Authorized"
    end
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def index
    @applications = RegisteredApplication.all
  end

  def new
    @application = RegisteredApplication.new
  end

    def create
      @application = current_user.registered_applications.build(registered_application_params)

      if @application.save
        flash[:notice] = "#{@application.name} created"
        redirect_to @application
      else
        flash.now[:error] = "Your application could not be created. Please try again."
        render :new
      end
    end

  def show
    @application = RegisteredApplication.find(params[:id])
    authorized? @application
    @events = @application.events.group_by(&:name)
  end

  def edit
    @application = RegisteredApplication.find(params[:id])
  end

    def update
      @application = RegisteredApplication.find(params[:id])

      if @application.update_attributes(registered_application_params)
        flash[:notice] = "#{@application.name} updated"
        redirect_to action: 'index'
      else
        flash.now[:error] = "The application could not be updated. Please try again."
        render :edit
      end
    end


  def destroy
    @application = RegisteredApplication.find(params[:id])

    if @application.destroy
      flash[:notice] = "Application '#{@application.name}' deleted"
      redirect_to action: 'index'
    else
      flash.now[:error] = "The application could not be deleted. Please try again"
      render :show
    end
  end

  private

    def registered_application_params
      params.require(:registered_application).permit(:name, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    flash.now[:alert] = warden.message if warden.message.present?
  end

  def create
    warden.authenticate!
    redirect_to root_url, notice: 'Logged in'
  end

  def destroy
    warden.logout
    redirect_to root_url, notice: 'Logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      warden.set_user(@user)
      UserMailer.registration_confirmation(@user).deliver_now
      redirect_to root_url, notice: 'Account created'
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user)
  end

    def update
      @user = User.find(current_user)

      if @user.update_attributes(user_params)
        redirect_to account_path, notice: "#{@user.email} preferences saved!"
      else
        flash.now[:error] = "There was a problem saving your preferences."
        render :edit
      end
    end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Pidgin
  %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-eval' => false
  = yield(:header)
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button{ type: 'button', class: 'navbar-toggle collapsed', 'data-toggle' => 'collapse', 'data-target' => 'static-navbar', 'aria-expanded' => 'false' }
          %span.sr-only Toggle Navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Pidgin", root_url, class: 'navbar-brand'

      .collapse.navbar-collapse#static-navbar
        %ul.nav.navbar-nav
          %li= link_to "Home", root_url
        %ul.nav.navbar-nav.navbar-right
          - if current_user
            %li.dropdown
              %a{ class:'dropdown-toggle', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' }
                #{current_user.email}
                %span.caret
              %ul.dropdown-menu
                %li= link_to "Applications", registered_applications_url
                %li= link_to "Sign Out", sign_out_url
          - else
            %li= link_to "Sign In", sign_in_url
            %li= link_to "Sign Up", sign_up_url

  - if flash[:error]
    .alert.alert-danger= flash[:error]
  - if flash[:alert]
    .alert.alert-warning= flash[:alert]
  - if flash[:notice]
    .alert.alert-success= flash[:notice]

  .container
    = yield

app/views/registered_applications/_chartdata.js.erb
<% colors = [151, 187, 205] %>
[
  <% @data.each do |name, date| %>
    {
      label: "<%= name %>",
      fillColor: "rgba( <%= colors.map! { |color| color - 20 }.join(",") %>, 0.2)",
      strokeColor: "rgba(151,187,205,1)",
      pointColor: "rgba(<%= colors.join(",") %>, 1)",
      pointStrokeColor: "#fff",
      pointHighlightFill: "#fff",
      pointHighlightStroke: "rgba(220,220,220,1)",
      data: <%= @data[name].values %>
    },
  <% end %>
]

app/views/registered_applications/edit.html.haml
.col-md-3

.col-md-6
  %h1.text-center Edit Application
  = form_for @application do |f|
    - if @application.errors.any?
      .alert.alert-danger
        %h4 There is a problem with the information you submitted
        %ul
          - @application.errors.full_messages do |msg|
            %li= msg
    = form_group_tag(@application.errors[:name]) do
      = f.label :application_name
      = f.text_field :name, class:'form-control', placeholder: "#{@application.name}"

    = form_group_tag(@application.errors[:url]) do
      = f.label :application_url
      = f.text_field :url, class:'form-control', placeholder: "#{@application.url}"

    .actions
      = f.submit "Submit"

.col-md-3

app/views/registered_applications/index.html.haml
.col-md-3

.col-md-6
  %h1.text-center Registered Applications
  %table.table.table-hover
    %thead
      %tr
        %th
          %h4 Name
        %th
          %h4 URL
        %th
    %tbody
      - @applications.each do |application|
        %tr
          %td= link_to "#{application.name}", application
          %td= application.url
          %td
            = link_to "Edit", edit_registered_application_path(application.id)
            |
            = link_to "Destroy", application, method: :delete
      %th
        %td
          %h4= link_to "New Application", new_registered_application_url
        %td

.col-md-3

app/views/registered_applications/new.html.haml
.col-md-3

.col-md-6
  %h1.text-center New Application
  = form_for @application do |f|
    - if @application.errors.any?
      .alert.alert-danger
        %h4 There is a problem with the information you submitted
        %ul
          - @application.errors.full_messages do |msg|
            %li= msg
    = form_group_tag(@application.errors[:name]) do
      = f.label :application_name
      = f.text_field :name, class:'form-control', placeholder: "Application Name"

    = form_group_tag(@application.errors[:url]) do
      = f.label :application_url
      = f.text_field :url, class:'form-control', placeholder: "Your Application's URL"

    .actions
      = f.submit "Submit"

.col-md-3

app/views/registered_applications/show.html.haml
- content_for(:header) do
  = javascript_include_tag 'Chart'

.col-md-3

.col-md-6
  %h1.text-center= @application.name
  %h4.text-center= @application.url
  %div
    %canvas#chart{ width: 470, height: 300 }
  .clearfix
  %table.table
    %thead
      %tr
        %th Event Name
        %th Count
    %tbody
      - @events.each do |key,val|
        %tr
          %td= key
          %td= val.count
  .clearfix
    %div#legend
  .clearfix
    = render partial: 'chartdata.js.erb', locals: {data: @data, sql: @sql}

.col-md-3

:javascript
  var ctx = document.getElementById("chart").getContext("2d");
  var data = {
    labels: #{@days.map { |day| day.to_date.strftime("%A") }},
    datasets: #{ render partial: 'chartdata.js.erb', locals: { data: @data } }
  };

  var newChart = new Chart(ctx).Line(data);

app/views/users/edit.html.haml
%h1 Edit Account
.col-md-4
  = form_for @user, url: account_path do |f|
    - if @user.errors.any?
      .alert.alert-danger
        %h4 There is a problem with the information you submitted.
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    = form_group_tag(@user.errors[:email]) do
      = f.label :email
      = f.email_field :email, class:'form-control', placeholder: "#{@user.email}"

    = form_group_tag(@user.errors[:current_password]) do
      = f.label :current_password
      = f.password_field :current_password, class:'form-control', placeholder: 'Current password'

    = form_group_tag(@user.errors[:password]) do
      = f.label :new_password
      = f.password_field :password, class:'form-control'

    = form_group_tag(@user.errors[:password]) do
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class:'form-control'

    .actions
      = f.submit "Submit"

.col-md-8

app/views/users/new.html.haml
%h1 Create Account

.col-md-4
  = form_for @user, url: sign_up_path do |f|
    - if @user.errors.any?
      .alert.alert-danger
        %h4 There is a problem with the information you submitted.
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

    = form_group_tag(@user.errors[:email]) do
      = f.label :email
      = f.email_field :email, class:'form-control', placeholder: 'Email'

    = form_group_tag(@user.errors[:password]) do
      = f.label :password
      = f.password_field :password, class:'form-control', placeholder: 'Password'

    = form_group_tag(@user.errors[:password]) do
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class:'form-control', placeholder: 'Password (again)'

    .actions
      = f.submit "Submit"

.col-md-8

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>